title: Maintaining Brains
tagline: Learn to maintain your brain through play!
maintained_by: Brain Health Lab
email: brainhealthlab@stfx.ca
department: Department of Psychology
institution: St. Francis Xavier University
location: Antigonish, Nova Scotia, Canada
